<def f='tensorflow/tensorflow/core/lib/core/errors.h' l='113' macro='1' type='::tensorflow::Status tensorflow::errors::DeadlineExceeded(Args... args)'/>
<use f='tensorflow/tensorflow/core/distributed_runtime/local_master.cc' l='40' u='c' c='_ZN10tensorflow12_GLOBAL__N_119WaitForNotificationEPNS_11CallOptionsExPNS_12NotificationE'/>
<use f='tensorflow/tensorflow/core/grappler/clusters/single_machine.cc' l='268' u='c' c='_ZN10tensorflow8grappler13SingleMachine14RunWithTimeoutERKSt6vectorISt4pairISsNS_6TensorEESaIS5_EERKS2_ISsSaISsEEPNS_11RunMetadataEx'/>
<use f='tensorflow/tensorflow/core/kernels/batch_kernels.cc' l='746' u='c' c='_ZN10tensorflow15UnbatchResource14EnforceTimeoutEv'/>
