<dec f='include/python3.5m/pyerrors.h' l='299' type='PyObject * PyErr_NewExceptionWithDoc(const char * name, const char * doc, PyObject * base, PyObject * dict)'/>
