<dec f='include/python3.5m/pyerrors.h' l='87' type='void PyErr_Clear()'/>
<use f='tensorflow/tensorflow/python/eager/pywrap_tensor.cc' l='106' u='c' c='_ZN12_GLOBAL__N_112CopyToDeviceEP16TFE_TensorHandleP7_objectS3_'/>
<use f='tensorflow/tensorflow/python/eager/pywrap_tensor.cc' l='235' u='c' c='EagerTensor_init'/>
<use f='tensorflow/tensorflow/python/eager/pywrap_tfe_src.cc' l='91' u='c' c='_ZN12_GLOBAL__N_118TensorShapeNumDimsEP7_object'/>
