<dec f='include/python3.5m/pyerrors.h' l='89' type='void PyErr_Restore(PyObject * , PyObject * , PyObject * )'/>
