<dec f='include/python3.5m/pyerrors.h' l='166' type='PyObject *'/>
<use f='tensorflow/tensorflow/python/lib/core/py_func.cc' l='196' u='r' c='_ZN10tensorflow12_GLOBAL__N_112DoCallPyFuncEPNS0_6PyCallEPb'/>
