<dec f='include/python3.5m/pyerrors.h' l='126' type='void PyException_SetContext(PyObject * , PyObject * )'/>
