<def f='tensorflow/tensorflow/core/distributed_runtime/rpc/grpc_state.h' l='37' ll='41' type='void tensorflow::RPCState::RPCState&lt;Response&gt;(::grpc::GenericStub * stub, ::grpc::CompletionQueue * cq, const ::grpc::string &amp; method, const protobuf::Message &amp; request, Response * response, StatusCallback done, tensorflow::CallOptions * call_opts)'/>
<use f='tensorflow/tensorflow/core/distributed_runtime/rpc/grpc_remote_worker.cc' l='190' u='c' c='_ZN10tensorflow16GrpcRemoteWorker12IssueRequestEPKN6google8protobuf7MessageEPS3_RKSsSt8functionIFvRKNS_6StatusEEEPNS_11CallOptionsE'/>
<use f='tensorflow/tensorflow/core/distributed_runtime/rpc/grpc_remote_worker.cc' l='196' u='c' c='_ZN10tensorflow16GrpcRemoteWorker12IssueRequestEPKN6google8protobuf7MessageEPNS_14TensorResponseERKSsSt8functionIFvRKNS_6StatusEEEPNS_11CallOptionsE'/>
<doc f='tensorflow/tensorflow/core/distributed_runtime/rpc/grpc_state.h' l='36'>// Default behavior is to set fail_fast = False and handle timeouts manually.</doc>
