<dec f='include/python3.5m/pyerrors.h' l='234' type='PyObject * PyErr_SetFromErrnoWithFilenameObjects(PyObject * , PyObject * , PyObject * )'/>
