<dec f='include/c++/5/bits/functexcept.h' l='105' type='void std::__throw_bad_function_call()'/>
<use f='include/c++/5/functional' l='2266' u='c' c='_ZNKSt8functionIFT_DpT0_EEclES2_'/>
<doc f='include/c++/5/bits/functexcept.h' l='103'>// Helpers for exception objects in &lt;functional&gt;</doc>
