<dec f='include/python3.5m/pyerrors.h' l='327' type='void PyErr_SetInterrupt()'/>
