<dec f='include/python3.5m/pyerrors.h' l='118' type='PyObject * PyException_GetTraceback(PyObject * )'/>
